audit_header: false
title: Antelope Valley Real Estate Video Blog with Rob Talbot
description: Our mission at Rob Talbot Real Estate Economist is to be your best resource for Antelope Valley real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Rob Talbot Real Estate Economist, your professional Antelope Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Rob Talbot
  title:
  license_number:
  about_markdown: |
        Rob Talbot is an Operating Principal with Keller Williams VIP Properties in Valencia, CA &amp; withKeller Williams Central in Northridge, CA. Rob began a career in real estate as a realtor in 2006. Rob built his real estate team to be completely leveraged using the MREA Business Models. In 2012, he became Team Leader of Keller Williams Antelope Valley where he stayed until 2018, during this time Rob delivered amazing results for that Market Center- they went from 265 agents to 486 which is an 83% increase, he grew that office to be #1 in Market Share, and they consistently share profits with their associates. Rob is also a Leadership Coach with KW MAPS Coaching. Rob travels to train, consult and coach associates, leadership, and other professionals on personal development and real estate related topics.
        
        • Real estate team values are God, Family, Business
        
        • Greater Antelope Valley Association President from 2013-2015
        
        • Served 6 years as a CAR board of directors
  brand: Rob Talbot Group
  brokerage: Keller Williams
  market: Antelope Valley
  address: 1401 W. Rancho Vista Blvd. Ste. B Palmdale, CA 93551
  phone: 661-435-8281
  phone_type:
  phone2:
  phone2_type:
  email: robtalbot@kw.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Antelope Valley Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Antelope Valley Home?"
    CTA_text2: "Search the entire MLS for your Antelope Valley home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://business.facebook.com/RobTalbotGroup/?business_id=10153283000255325
  linkedin_url: https://www.linkedin.com/in/rob-talbot-46893432/
  youtube_url: https://www.youtube.com/channel/UCOnHDLsuyXYbXYMuQXY2vDQ?view_as=subscriber
  twitter_url:
  instagram_url: https://www.instagram.com/robtalbotgroup/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Antelope Valley Real Estate Podcast with Rob Talbot'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Santa Clarita Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Rob Talbot Real Estate Economist - your professional Santa Clarita Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Santa Clarita Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Rob Talbot'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#8c181b'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#332d53'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
